name: Deploy

on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Invoke Deploy
        uses: akhileshns/heroku-deploy@v3.12.12s
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "payments-prodoops"
          heroku_email: "cmilfont@gmail.com"
          branch: "master"
          healthcheck: "https://payments-prodoops.herokuapp.com/s"
          checkstring: "Hello World!"
          delay: 5
          rollbackonhealthcheckfailed: true
